---
- name: install vim
  yum: pkg=vim-nox state=latest

- name: install pip
  yum: pkg=python-pip state=latest

- name: install boto
  pip: name=boto state=latest

- name: install httpd
  yum: pkg=httpd state=latest
