---
- name: Install packages
  hosts: all
  tasks:

  - name: Install packages  
    yum: name={{ item}} state=present
    with_items:
      - httpd 
      - httpd-devel 
      - php 
      - php-xml 
      - php-mcrypt 
      - php-soap 
      - php-dba 
      - php-pecl-memcache 
      - php-devel 
      - php-mysql 
      - php-xmlrpc 
      - php-pdo 
      - php-gd 
      - php-mbstring 
      - php-pear
      - mod_ssl
      - php-pecl-apc
      - memcached

  - name: Create DocumentRoot
    file: path=/home/sites/tokidoki.it/httpdocs/shop owner=ec2-user group=ec2-user mode=0775 state=directory

  - name: Sync apache config over
    synchronize: mode=pull src=/etc/httpd/conf dest=/etc/httpd/
  
  - name: Sync php config over
    synchronize: mode=pull src=/etc/php.* dest=/etc/

  - name: Sync DocumentRoot
    synchronize: mode=pull src=/home/sites/tokidoki.it/httpdocs/shop/ dest=/home/sites/tokidoki.it/httpdocs/shop/